### ISSUE TITLE
Throw error when access into a js project where is no typescript module

### ISSUE THREAD

**Issue by wenjoy** [pmizio/typescript-tools.nvim#285] opened 2024-07-18 03:42 UTC
I failed to find config to suppress this error. 

Is there a way? Or else it would be nice to support to suppress this error, because in most cases we may not install typescript module if not necessary.

I know I can install a typescript globally, but in that way I'm concerned about how can I know which version I'm using in a typescript project? global one or local one?

<img width="1470" alt="image" src="https://github.com/user-attachments/assets/32817d1e-1cbd-4568-832a-8735eb5e21fd">

**Comment by KostkaBrukowa** [comment] 2024-07-18 05:50
This is duplicate of #251 
And if you have local installation and global installation typescript-tools will choose local one (basically global installation is sort of fallback.

**Closed by KostkaBrukowa** 2024-07-18 05:50 UTC
