### ISSUE TITLE
Request for Custom Command to Rename Files

### ISSUE THREAD

**Issue by Armadillidiid** [pmizio/typescript-tools.nvim#172] opened 2023-10-12 06:56 UTC
I'd like to propose the addition of a custom command similar to the one provided by the deprecated typescript.nvim plugin, specifically the `TSRenameFile` command. This command was incredibly useful for quickly renaming files within a project.

Being able to rename files directly from within the editor greatly streamlines the development process. This feature would be greatly appreciated .

**Comment by pmizio** [comment] 2023-10-12 07:32
Duplicate of: https://github.com/pmizio/typescript-tools.nvim/issues/94
Will be resolved by: https://github.com/pmizio/typescript-tools.nvim/pull/170

**Closed by pmizio** 2023-10-12 07:32 UTC
Labels: duplicate
