### ISSUE TITLE
not support javascript projects?

### ISSUE THREAD

**Issue by henryy-el** [pmizio/typescript-tools.nvim#216] opened 2024-01-11 23:05 UTC
I'm working on a project that uses javascript, but it seems your tools are not supported?

**Comment by pmizio** [comment] 2024-01-12 07:39
Probably duplicate of https://github.com/pmizio/typescript-tools.nvim/issues/199#issuecomment-1845177592.
Please let me know if linked comment helps.

**Closed** 2024-06-19 12:28 UTC
