### ISSUE TITLE
Opening a non-ts/js buffer after typescript tools is running, triggers a notificiation about codelens

### ISSUE THREAD

**Issue by kmoschcau** [pmizio/typescript-tools.nvim#173] opened 2023-10-12 08:40 UTC
I have configured my typescript tools codelens like so:

```lua
require("typescript-tools").setup {
  settings = {
    code_lens = "all",
    disable_member_code_lens = false,
  },
}
```

This works fine when opening a JS or TS buffer. But once the server is running,
as soon as I open a new non-JS/TS buffer, it triggers the following
notification:

```
method textDocument/codeLens is not supported by any of the servers registered for the current buffer
```

The expectation is that typescript-tools does not try to trigger codelens in
buffers where the server is not active.

**Comment by pmizio** [comment] 2023-10-13 11:36
@kmoschcau Ok so, I cannot reproduce it but in [this pr](https://github.com/pmizio/typescript-tools.nvim/pull/177) I added additional filter to autocmd which call `vim.lsp.codelens.refresh()`.
If this won't fix your issue then it is probably something in your config, by this I mean some LSP which wrongly declare support for codelens.
We only call `vim.lsp.codelens.refresh()` and it should ask all attached buffers for codelens, this logic isn't on our end.

Please take a look and let me know if it helps.

**Comment by kmoschcau** [comment] 2023-10-13 13:01
Jep, that change fixes it.

**Closed** 2023-10-13 13:17 UTC
Labels: bug
